name: 'PR Size Labels'
description: 'Label a PR based on the number of changes in the PR'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  xs_max_size:
    description: 'Extra Small'
    required: false
    default: '10'
  s_max_size:
    description: 'Small'
    required: false
    default: '30'
  m_max_size:
    description: 'Medium'
    required: false
    default: '100'
  l_max_size:
    description: 'Large'
    required: false
    default: '500'
  xl_max_size:
    description: 'Extra Large'
    required: false
    default: '1000'
  fail_if_xxl:
    description: 'Fail if XXL'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.xs_max_size }}
    - ${{ inputs.s_max_size }}
    - ${{ inputs.m_max_size }}
    - ${{ inputs.l_max_size }}
    - ${{ inputs.xl_max_size }}
    - ${{ inputs.fail_if_xl }}
